### ISSUE TITLE
Check JWT Token validation

### ISSUE THREAD

**Issue by cklein2** [th-koeln/open-product-evaluation-client#4]
schon im branch bugfix rumgespielt, aber null zufrieden damit. oder ich habe einen Denkfehler. was ist mit refresh-token?

**Comment by fdaugs** [comment]
Was genau ist denn das Problem? Theoretisch wäre der Ablauf doch so:

Ist im Localstorage ein Token?
Ja -> Versuchen damit die Surveys zu holen, wenn das geht, ist alles ok, wenn nicht weiter zu Nein =>
Nein ->Token löschen, create Client aufrufen und token in local Storage speichern.
