### ISSUE TITLE
Some visualization of already existing votes? 

### ISSUE THREAD

**Issue by cklein2** [th-koeln/open-product-evaluation-client#5]
Ist halt echt 1:1 von der Idee dann wie der alte Client von mir. Andere Ideen?

**Comment by fdaugs** [comment]
Wir können das ja dann mit lustiger Hardware verbinden. Die Idee mit den Barcode-Scannern kennst du ja. Ich versuche die diese Woche mal zu organisieren. Und dann könnten wir das Design auch in Richtung Supermarkt ausrichten. Die Frage ist halt, ob das hier ein Tutorail/Template-Client wird oder eine "Was alles Möglich ist /demo client"...

**Comment by slemke** [comment]
Der Grundgedanke war ja das es ein Referenzclient ist. Also idealerweise mindestens die Beispielkompositionen aus dem Server Wiki zeigt. Alles andere hängt von euch ab.
