### ISSUE TITLE
Order of answering questions

### ISSUE THREAD

**Issue by cklein2** [th-koeln/open-product-evaluation-client#6]
Wie machen wir den Ablauf der Umfrage: 
1. direkt pro Frage antworten --> nur dann kann man weiter, sprich man kann auch nicht zurück, evtl. Notification wenn man nichts gewählt hat, oder Button "enthalten"
2. Weiter egal ob geantwortet wurde oder nicht. Evtl. am Schluss Möglichkeit haben die offenen Fragen doch noch zu beantworten?
3. ....

**Comment by fdaugs** [comment]
Ich würde dirket auf die Frage antworten lassen.
